---
language: node_js
install: true
cache: yarn

node_js:
  - '6'
  - '8'
  - '10'

install:
  - yarn install

script:
  - yarn relay
  - yarn test

after_success:
  - bash <(curl -s https://codecov.io/bash)